# https://taskfile.dev
version: '3'

vars:
  WORKING_DIR:
    sh: pwd

  CORE_DIR: ../core/generated
  UI_DIR: ../ui/src/gen
  GENERATED_DIR: generated

tasks:
  geno:
    desc: generate files no moves
    deps: [ build ]
    cmds:
      - docker run --rm -v "{{.WORKING_DIR}}:/workspace" protobuilder:latest

  gen:
    desc: generate and copy out generated files and remove source generated dir
    deps: [ geno ]
    sources:
      - protos/**/
    cmds:
      - task: go
      - task: web

  go:
    desc: Copy generated Go files to core directory
    cmds:
      - task: _copy
        vars:
          TARGET_DIR: '{{.CORE_DIR}}'
          SOURCE_PATTERN: '{{.GENERATED_DIR}}/go/*'

  web:
    desc: Copy generated web files to UI directory
    cmds:
      - task: _copy
        vars:
          TARGET_DIR: '{{.UI_DIR}}'
          SOURCE_PATTERN: '{{.GENERATED_DIR}}/web/*'

  _copy:
    internal: true
    vars:
      TARGET_DIR: '{{.TARGET_DIR}}'
      SOURCE_PATTERN: '{{.SOURCE_PATTERN}}'
    cmds:
      - coreutils rm -f -r {{.TARGET_DIR}}/*
      - coreutils mkdir -p {{.TARGET_DIR}}
      - coreutils cp -r {{.SOURCE_PATTERN}} {{.TARGET_DIR}}/

  it:
    desc: drop into a shell and interact with the image. CTRL+D to exit
    deps: [ build ]
    cmds:
      - docker run --rm --name gouda_grpc_shell -v "{{.WORKING_DIR}}:/workspace" -it protobuilder:latest /bin/bash

  build:
    desc: Builds the core docker image with the generated tools installed
    cmds:
      - docker build . -t protobuilder:latest

  bpsh:
    desc: build and push
    cmds:
      - make build
      - make push
