name: dockman
services:
  dockman:
    container_name: dockman
    image: ghcr.io/ra341/dockman:dev
    volumes:
      - ./stacks:/stacks
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/ssh:/app/config/ssh
      - ./hosts.yaml:/app/config/hosts.yaml
    environment:
      - DOCKMAN_COMPOSE_ROOT=/stacks
      - DOCKMAN_AUTH_ENABLE=false
    ports:
      - "8432:8866"
