name: Action-Native-build

on:
  workflow_call:
    inputs:
      os:
        description: 'The operating system to run the build on (e.g., ubuntu-latest, windows-latest)'
        required: true
        type: string
      tag_name:
        description: 'The release tag name for uploading assets'
        required: true
        type: string
      go_version:
        description: 'Go version to use'
        required: false
        type: string
        default: '1.24'

jobs:
  build:
    name: Build Dockman for ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    permissions:
      contents: write  # Allows checking out code and uploading release assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
          cache-dependency-path: |
            core/go.sum

      - name: Get build date
        id: date
        run: echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        shell: bash  # Force bash on all platforms

      - name: Build Dockman
        env:
          COMMIT_INFO: ${{ github.sha }}
          BRANCH: ${{ github.ref_name }}
          BUILD_DATE: ${{ steps.date.outputs.BUILD_DATE }}
        run: |
          go build -ldflags "-s -w \
              -X github.com/RA341/dockman/internal/info.Version=${{ inputs.tag_name }} \
              -X github.com/RA341/dockman/internal/info.CommitInfo=${COMMIT_INFO} \
              -X github.com/RA341/dockman/internal/info.BuildDate=${BUILD_DATE} \ 
              -X github.com/RA341/dockman/internal/info.Branch=${BRANCH}" \
          -o dockman "./cmd/server/main.go"
        shell: bash  # Force bash on all platforms

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            output/*
            dockman*
          tag_name: ${{ inputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}