name: Canary-Build

on:
  push:
    branches:
      - main # publish a dev build on main
    paths:
      - Dockerfile
      - Dockerfile.updater
      - .github/workflows/action-docker.yml
      - build-canary.yml
      - core/**
      - ui/**

permissions:
  contents: read   # To checkout the repository
  packages: write  # To push Docker images to GHCR

jobs:
  build:
    strategy:
      matrix:
        include:
          - title: dockman
            version_tag: canary
            source_branch: ${{ github.ref_name }}
            dockerfile: Dockerfile
          - title: dockman/updater
            version_tag: canary
            source_branch: ${{ github.ref_name }}
            dockerfile: Dockerfile.updater

    name: Build ${{ matrix.title }}
    uses: ./.github/workflows/action-docker.yml
    with:
      title: ${{ matrix.title }}
      version_tag: ${{ matrix.version_tag }}
      source_branch: ${{ matrix.source_branch }}
      dockerfile: ${{ matrix.dockerfile }}
    secrets: inherit

#  build_and_release_linux:
#    name: Build and Release for Linux
#    uses: ./.github/workflows/action-gouda-native.yml
#    with:
#      os: ubuntu-latest
#      flutter_version: '3.27.1'
#      go_version: '1.24'
#      tag_name: dev
#    secrets: inherit