name: Develop-Build

on:
  push:
    branches:
      - dev
    paths:
      - Dockerfile
      - Dockerfile.updater
      - .github/workflows/action-docker.yml
      - build-dev.yml
      - core/**
      - ui/**

permissions:
  contents: read   # To checkout the repository
  packages: write  # To push Docker images to GHCR

jobs:
  dockman-docker:
    name: Build docker dev build
    uses: ./.github/workflows/action-docker.yml
    with:
      title: 'dockman'
      version_tag: develop
      source_branch: ${{ github.ref_name }}
    secrets: inherit

  dockman-updater:
    name: Build docker dev build
    uses: ./.github/workflows/action-docker.yml
    with:
      title: 'dockman/updater'
      version_tag: develop
      source_branch: ${{ github.ref_name }}
      dockerfile: Dockerfile.updater
    secrets: inherit

#  build_and_release_linux:
#    name: Build and Release for Linux
#    uses: ./.github/workflows/action-gouda-native.yml
#    with:
#      os: ubuntu-latest
#      flutter_version: '3.27.1'
#      go_version: '1.24'
#      tag_name: dev
#    secrets: inherit