name: dockman-updater
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile.updater
      - core/cmd/updater/**
      - .github/workflows/updater-workflow.yml

jobs:
  build-and-push:
    name: Build and Push Docker for ${{ github.repository }}/updater
    runs-on: ubuntu-latest
    permissions:
      contents: read   # To checkout the repository
      packages: write  # To push Docker images to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker image tags and N
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/updater
          tags: |
            type=raw,value=latest,enable=true
          labels: |
            org.opencontainers.image.title=Dockman updater
            org.opencontainers.image.description=Docker image for dockman updater.
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #          platforms: "linux/amd64,linux/arm64" todo takes a long time
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile.updater

      - name: Echo image details
        if: success()
        run: |
          echo "🚀 Docker image build and push complete for: ghcr.io/${{ github.repository }}/updater"
          echo "🏷️ Tags created:"
          echo "${{ steps.meta.outputs.tags }}"
          echo "📋 Labels applied:"
          echo "${{ steps.meta.outputs.labels }}"
